---

- name: Set Custom Default Index
  ansible.builtin.uri:
    url: 'http://{{ ansible_default_ipv4.address }}:5601/api/kibana/settings'
    method: POST
    body:
      changes:
        defaultIndex: '{{ kibana_custom_default_index }}'
    body_format: json
    headers:
      kbn-version: 8.19.11
      Content-Type: application/json
  register: result
- ansible.builtin.debug:
    msg: "setting new custom Index to {{ kibana_custom_default_index }}"
