---
# defaults file for elastic-repos
elasticstack_release: 8
elasticstack_full_stack: true
elasticstack_variant: elastic

elasticstack_rpm_workaround: false

elasticstack_enable_repos: true
elasticstack_no_log: true
